import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import "./globals.css";
import Web3ModalProvider from "@/context";
const inter = Inter({ subsets: ["latin"] });
import { headers } from 'next/headers'
import { cookieToInitialState } from 'wagmi'
import { config } from "@/config";

export const metadata: Metadata = {
  title: "PERSAKA DAO voting system",
  description: "Generated by create next app",
};

// import { createTheme } from '@mui/material/styles';

// let theme = createTheme({
//   palette: {
//     primary: {
//       main: '#0052cc',
//     },
//     secondary: {
//       main: '#edf2ff',
//     },
//   },
// });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))
  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3ModalProvider>
          <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
        </Web3ModalProvider>
      </body>
    </html>
  );
}
